name: deploy b/prd
on:
  push:
    branches:
      - main
    paths:
      - files/b.txt
defaults:
  run:
    shell: bash
jobs:
  prd:
    runs-on: ubuntu-latest
    environment: b/prd
    steps:
      - uses: actions/checkout@v6
      - run: cat files/b.txt
