name: deploy b/stg
on:
  push:
    branches:
      - main
    paths:
      - files/b.txt
defaults:
  run:
    shell: bash
jobs:
  stg:
    runs-on: ubuntu-latest
    environment: b/stg
    steps:
      - run: cat files/b.txt
